#112 - reconcile removed associations on subsequent upserts
greenbits/brick pull request #119
Opened 2021-01-03 22:42 UTC by tshedor

2021-01-29 08:53 UTC, polRk requested changes
Missing single quote

2021-01-29 08:53 UTC, polRk commented on packages/brick_sqlite_generators/lib/src/sqlite_serialize.dart
> +        final ${field.name}OldIds = ${field.name}OldColumns?.map((a) => a[$joinsForeignColumn]) ?? [];
`a['$joinsForeignColumn']`

2021-01-31 00:40 UTC, tshedor commented on packages/brick_sqlite_generators/lib/src/sqlite_serialize.dart
> +        final ${field.name}OldIds = ${field.name}OldColumns?.map((a) => a[$joinsForeignColumn]) ?? [];
@polRk added

2021-01-31 10:28 UTC, polRk approved these changes
In my project, it works!

2021-02-06 23:21 UTC, tshedor commented
@polRk I updated this just a little bit - since calling `.clear()` on an instance is permitted in Dart but isn't true to the ideal of treating `final` as immutable, for associations where you want to call `.clear()` you should be sure to specify those fields as `var fieldName` or `List<YourAssociationName> fieldName`.

2021-02-09 21:56 UTC, merged